### PR TITLE
Revisions on intro of colab demo

### PR DESCRIPTION
**Pull request by neubig**
# Description

This PR makes some revisions on the intro of the colab demo, up to the dataset retriever part.

@zhaochenyang20 : please review this and if it looks good merge this in to `add_colab_demo`, and then I would like to remove the mandatory command line manipulation from the various parts, starting with the dataset retriever: https://github.com/neulab/prompt2model/issues/292

# References

- #290 

# Blocked by

- NA

### CODE REVIEW

**Comment by zhaochenyang20** [comment]
Two things I want to make sure:

1. I am not so familiar with colab. Thus I am not so clear how to follow this line:

image

Is there a simpler way?

2. I used `git clone` and then `pip install .` because sometimes I run into some errors like "model_info" director not found. I don't know if this new demo could retrieved the right model without git pulling our repo and fetching the `model_info.tgz`. 🤔

**Comment by neubig** [comment]
Hey, thanks @zhaochenyang20! Currently I’m doing all the testing locally by just running the jupyter notebook on my local machine. Once it works locally I think we can re-test it on colab and resolve the remaining issues if that's OK.

**Comment by zhaochenyang20** [comment]
Okay! I will approve this after you test it on Colab. 🤔

**Comment by neubig** [comment]
Let's approve now since it's just a PR into another PR (`add_colab_demo`).

**Pull request merged**
