### PR TITLE
Fix generator progress bar

### PR DESCRIPTION
**Pull request by neubig**
# Description

The generator progress bar was broken, making it look like progress was faster than it actually was.

# References

- Fixes https://github.com/neulab/prompt2model/issues/333

# Blocked by

- https://github.com/neulab/prompt2model/pull/335

### CODE REVIEW

**Comment by zhaochenyang20** [comment]
I have once encountered this. Just use p.update(len - p.t) fix it 🤔

**Comment by neubig** [comment]
Yeah, that's basically what this PR does. You can see the diff here: https://github.com/neulab/prompt2model/compare/refactor_dataset_generator..fix_generator_progress_bar

**Comment by viswavi** [comment]
@neubig do you need to re-merge main into this branch? It says there are 1k lines added which seems wrong from the description of this PR.

**Comment by neubig** [comment]
This builds of 335 and 336 so they should be reviewed first, but you can also look at the diff that I posted above too

**Review by zhaochenyang20 — APPROVED** [review]
Cool!

**Review by viswavi — APPROVED** [review]
LGTM

**Pull request merged**
